name: Vivid Voice
favicon: null
layout_spectrum: 0.4309101279359311
typography_spectrum: 0.4460071020293981
title: Vivid Voice
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.4831410935148597
  lightness: 0.11955548287369311
  saturation: 0.6665327709633857
  rhythmicContrast: 0.3734366574790329
purpose: []
